export const ROUTES = {
    CRM: "/crm",
    INDEX: "/",
    AUTH: "/auth",
    CHAT: "/chat",
    POST: "/post",
    TASK: "/task",
    PROFILE: "/profile",
    SETTINGS: "/settings",
    FAVORITES: "/favorites",
    MY_INVITES: "/my-invites",
    INVITE: "/invites/accept",
    MY_TASKS: "/crm/my-tasks",
    CALENDAR: "/crm/calendar",
    EXECUTORS: "/crm/executors",
    MANAGE_POSTS: "/manage-posts",
    MY_RESPONSES: "/my-responses",
    SETTINGS_APPS: "/settings/apps",
    PUBLICATIONS: "/crm/publications",
    SETTINGS_GENERAL: "/settings/general",
    SETTINGS_MEMBERS: "/settings/members",
    SETTINGS_BILLING: "/settings/billing",
    SETTINGS_ACCOUNT: "/settings/account",
    SETTINGS_SECURITY: "/settings/security",
    MANAGE_APPLICATION: "/manage-application",
    SETTINGS_NOTIFICATION: "/settings/notification",
    SETTINGS_LANGUAGE: "/settings/language-and-region",
    SETTINGS_CRM: "/settings/crm",
    SETTINGS_CRM_TASKS: "/settings/crm/tasks",
    SETTINGS_CRM_PIPELINE: "/settings/crm/pipeline",
    SETTINGS_CRM_AUTOMATION: "/settings/crm/automation",
} as const;


