export const MAX_DASHBOARD_LIST_ITEMS = 5;

export const DASHBOARD_TABLE_PAGE_SIZE = 20;

export const MOBILE_DASHBOARD_TABLE_PAGE_SIZE = 6;

export const DASHBOARD_ACTIVITY_PAGE_SIZE = 20;

export const DASHBOARD_COMMENTS_ITEMS_LIMIT = 10;

export const DASHBOARD_COMMENTS_THREAD_LIMIT = 10;

export const DASHBOARD_COMMENT_CARD_COLLAPSE_MS = 280;
